project:
  type: website
  output-dir: docs

website:
  title: "Cozmina Secula"
  open-graph: true
  navbar:
    title: false
    background: "#eee"
    left: 
      - href: about.qmd
        text: About
    right:
      - href: index.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
      - icon: github
        href: https://github.com/CozminaSecula
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
format:
  html:
    theme: custom.scss
    css: styles.css
cookie-consent: true
editor: visual


