project:
  type: website
  output-dir: docs

website:
  title: "Cozmina Secula"
  open-graph: true
  
  navbar:
    title: false
    background: "#eee"
    left: 
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
      - icon: github
        href: https://github.com/CozminaSecula
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
  page-footer: 
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Github Repo](https://github.com/CozminaSecula/blog){target="_blank"}</strong></span>
    center: |
      <span class="container"><strong>[Contact Cozmina Secula](mailto:cozmina.secula@gmail.com){target="_blank"}</strong></span>
    background: "#eee"
  favicon: "profile.jpg"
  
format:
  html:
    theme: custom.scss
    css: styles.css

editor: visual

   
