project:
  type: website
  output-dir: docs


website:
  title: "Making sense of data"
  open-graph: true
  
  page-navigation: true
  

  navbar:
    title: false
    background: "#eee"
    pinned: true
    left: 
      - text: About
        href: index.qmd
      - text: Posts
        href: posts.qmd
      - text: Weekly DataViz
        href: weekly_dataviz.qmd

      
    right: 
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
      - icon: github
        href: https://github.com/CozminaSecula

 
  page-footer: 
    left: >-
      &#169; 2024 Cozmina Secula &#8729; Made with [Quarto](https://quarto.org)
 

      
format:
  html:
    theme: custom.scss
    css: styles.css
    include-before-body: translate-widget.html


editor: visual

   
