project:
  type: website
  output-dir: docs


website:
  title: "Making sense of data"
  open-graph: true
  
  page-navigation: true
  

  navbar:
    title: false
    background: "#eee"
    pinned: true
    left: 
      - href: index.qmd
        text: About
      - href: posts.qmd
        text: Posts
      - href: notes/notes.qmd
        text: Learning resources
      
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
      - icon: github
        href: https://github.com/CozminaSecula
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
 
 
  page-footer: 
    left: >-
      &#169; 2024 Cozmina Secula &#8729; Made with [Quarto](https://quarto.org)
 
  sidebar: 
    - id: Learning resources
      title: "Learning resources"
      collapse-level: 2
      style: "floating"
      align: left
      contents:
       - notes/notes.qmd
       - notes/analytics-project.qmd
       - notes/R-resources.qmd
       - notes/quarto-tools.qmd

     
      
format:
  html:
    theme: custom.scss
    css: styles.css
    include-before-body: translate-widget.html
    grid: 
      sidebar-width: 200px

editor: visual

   
