<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.514">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Discover how to extract valuable insights using summary statistics and the independent samples t-test, with a case study on team diversity within a large organization.">
<title>Cozmina Secula - Unlocking Insights (II): Analyzing Data with Summary Statistics and Independent Samples t-Test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Cozmina Secula - Unlocking Insights (II): Analyzing Data with Summary Statistics and Independent Samples t-Test">
<meta property="og:description" content="Discover how to extract valuable insights using summary statistics and the independent samples t-test, with a case study on team diversity within a large organization.">
<meta property="og:site_name" content="Cozmina Secula">
</head>
<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../notes.html"> 
<span class="menu-text">Notes</span></a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/cozminasecula/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/CozminaSecula"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:cozmina.secula@gmail.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full"><div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Unlocking Insights (II): Analyzing Data with Summary Statistics and Independent Samples t-Test</h1>
                  <div>
        <div class="description">
          Discover how to extract valuable insights using summary statistics and the independent samples t-test, with a case study on team diversity within a large organization.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">summary statistics</div>
                <div class="quarto-category">independent samples t-test</div>
                <div class="quarto-category">continuous variable</div>
                <div class="quarto-category">categorical variable</div>
                <div class="quarto-category">quantitative analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#overview-of-the-content" id="toc-overview-of-the-content" class="nav-link active" data-scroll-target="#overview-of-the-content">Overview of the Content</a></li>
  <li><a href="#problem-statement" id="toc-problem-statement" class="nav-link" data-scroll-target="#problem-statement">Problem Statement</a></li>
  <li><a href="#data-preparation-and-exploration-1" id="toc-data-preparation-and-exploration-1" class="nav-link" data-scroll-target="#data-preparation-and-exploration-1">Data Preparation and Exploration</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary statistics</a></li>
  <li><a href="#independent-samples-t-test" id="toc-independent-samples-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test">Independent Samples t-Test</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="slides1.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content"><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Translate Widget</title>
<div id="google_translate_element"></div>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement(
                {pageLanguage: 'en'},
                'google_translate_element'
            );
        }
    </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script><section id="overview-of-the-content" class="level1"><h1>Overview of the Content</h1>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors

Attaching package: 'kableExtra'


The following object is masked from 'package:dplyr':

    group_rows


Loading required package: carData


Attaching package: 'car'


The following object is masked from 'package:dplyr':

    recode


The following object is masked from 'package:purrr':

    some</code></pre>
</div>
</div>
<section id="introducing-two-distinct-tools-for-data-analysis-with-numerical-and-categorical-data-using-r" class="level2"><h2 class="anchored" data-anchor-id="introducing-two-distinct-tools-for-data-analysis-with-numerical-and-categorical-data-using-r">Introducing two distinct tools for data analysis with numerical and categorical data using R</h2>
<ul>
<li>Summary statistics</li>
<li>Independent samples t-test</li>
</ul></section><section id="case-study" class="level2"><h2 class="anchored" data-anchor-id="case-study">Case study</h2>
<ul>
<li>Focused on diversity and inclusion (D&amp;I)</li>
<li>Sourced from the book <a href="https://www.amazon.com/Predictive-HR-Analytics-Mastering-Metric/dp/0749473916">Predictive HR Analytics : Mastering the HR Metric</a>
</li>
<li>With data available <a href="https://www.koganpage.com/hr-learning-development/predictive-hr-analytics-9780749484446">here</a>
</li>
</ul></section><section id="data-preparation-and-exploration" class="level2"><h2 class="anchored" data-anchor-id="data-preparation-and-exploration">Data preparation and exploration</h2>
<ul>
<li>Packages: <code>tidyverse</code>, <code>kableExtra</code>, <code>car</code>, <code>paleteer</code>
</li>
<li>Data preparation</li>
<li>Summary statistics</li>
<li>Data visualization</li>
<li>Independent samples t-test</li>
</ul></section></section><section id="problem-statement" class="level1"><h1>Problem Statement</h1>
<section id="the-goal" class="level2"><h2 class="anchored" data-anchor-id="the-goal">The Goal</h2>
<div class="goal">
<div class="small">
<p>A hypothetical company aims to employ scientific methods and procedures to tackle a significant people problem: employee diversity. It recognizes that:</p>
</div>
</div>
<div class="small">
<ul>
<li>
<p><strong>Commercial Perspective</strong></p>
<ul>
<li>A more diverse workforce can provide a competitive advantage by enhancing the organization’s understanding of its customers, consequently improving overall performance.</li>
</ul>
</li>
<li>
<p><strong>People Perspective</strong></p>
<ul>
<li>The organization gains access to a broader candidate pool, increases employee engagement, and elevates retention rates.</li>
</ul>
</li>
</ul>
</div>
</section><section id="the-research-question" class="level2"><h2 class="anchored" data-anchor-id="the-research-question">The research question</h2>
<p><br></p>
<div class="goal">
<p>How does the distribution of Black, Asian, or Minority Ethnic (BAME) employees vary across different professions?</p>
</div>
</section></section><section id="data-preparation-and-exploration-1" class="level1"><h1>Data Preparation and Exploration</h1>
<section id="look-at-the-data---the-structure" class="level2"><h2 class="anchored" data-anchor-id="look-at-the-data---the-structure">Look at the data - The structure</h2>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">diversity</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"../2023-10-11-summary-statistics-and-t-test/diversity2.csv"</span><span class="op">)</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">diversity</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 928
Columns: 30
$ DepartmentGroupNumber &lt;dbl&gt; 18, 19, 29, 30, 35, 37, 44, 45, 47, 50, 51, 63, …
$ GroupSize             &lt;dbl&gt; 18, 28, 11, 17, 32, 60, 23, 36, 32, 70, 52, 15, …
$ PercentMale           &lt;dbl&gt; 65, 67, 33, 32, 18, 65, 15, 26, 65, 5, 75, 50, 5…
$ BAME                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ NumberTeamLeads       &lt;dbl&gt; 3, 4, 2, 2, 5, 9, 3, 5, 5, 10, 7, 2, 4, 3, 9, 7,…
$ NumberFeMaleTeamLeads &lt;dbl&gt; 1, 0, 0, 0, 3, 0, 1, 0, 0, 2, 0, 0, 1, 0, 1, 0, …
$ Location              &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 2, 2, …
$ LondonorNot           &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, …
$ Function              &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ EMPsurvEngage_1       &lt;dbl&gt; 100, 96, 100, 100, 81, 97, 91, 100, 91, 97, 92, …
$ EMPsurvEngage_2       &lt;dbl&gt; 100, 86, 91, 100, 69, 97, 100, 94, 88, 97, 94, 1…
$ EMPsurvEngage_3       &lt;dbl&gt; 94, 86, 100, 100, 72, 87, 100, 89, 91, 93, 98, 9…
$ EMPsurvEngage_4       &lt;dbl&gt; 78, 54, 82, 94, 44, 92, 87, 97, 81, 90, 98, 87, …
$ EMPsurvEngage_5       &lt;dbl&gt; 100, 96, 100, 100, 81, 97, 100, 97, 97, 99, 94, …
$ EMPsurvEngage_6       &lt;dbl&gt; 94, 57, 82, 88, 44, 78, 87, 94, 72, 90, 88, 87, …
$ EMPsurvEngage_7       &lt;dbl&gt; 89, 89, 100, 100, 84, 92, 96, 97, 94, 99, 98, 10…
$ EMPsurvEngage_8       &lt;dbl&gt; 72, 82, 73, 88, 38, 55, 91, 69, 69, 80, 69, 80, …
$ EMPsurvEngage_9       &lt;dbl&gt; 78, 82, 91, 94, 47, 83, 96, 78, 81, 93, 85, 93, …
$ EMPsurvEngagement     &lt;dbl&gt; 89, 81, 91, 96, 62, 86, 94, 91, 85, 93, 91, 92, …
$ EMPorgIntegrity1      &lt;dbl&gt; 72, 75, 73, 100, 59, 87, 100, 61, 69, 69, 67, 60…
$ EMPorgIntegrity2      &lt;dbl&gt; 78, 86, 91, 100, 81, 92, 100, 89, 91, 94, 92, 10…
$ EMPorgIntegrity3      &lt;dbl&gt; 89, 89, 91, 100, 88, 93, 100, 89, 97, 97, 94, 10…
$ EMPorgIntegrity4      &lt;dbl&gt; 89, 89, 91, 100, 78, 80, 100, 81, 78, 80, 80, 93…
$ EMPorgIntegrity5      &lt;dbl&gt; 18, 19, 29, 30, 35, 37, 44, 45, 47, 50, 51, 63, …
$ EmpSurvOrgIntegrity   &lt;dbl&gt; 69.2, 71.6, 75.0, 86.0, 68.2, 77.8, 88.8, 73.0, …
$ EMPsurvSUP1           &lt;dbl&gt; 72, 79, 73, 100, 81, 88, 100, 75, 78, 96, 98, 87…
$ EMPsurvSUP2           &lt;dbl&gt; 89, 79, 91, 100, 78, 92, 100, 83, 94, 96, 94, 93…
$ EMPsurvSUP3           &lt;dbl&gt; 89, 64, 73, 100, 72, 78, 96, 78, 72, 90, 94, 100…
$ EMPsurvSUP4           &lt;dbl&gt; 83, 82, 73, 100, 75, 87, 100, 78, 84, 91, 98, 80…
$ EmpSurvSupervisor     &lt;dbl&gt; 83.25, 76.00, 77.50, 100.00, 76.50, 86.25, 99.00…</code></pre>
</div>
</div>
<div class="small">
<ul>
<li>The organization comprises 29,976 employees in two functional areas across the UK, and these employees are organized into 928 teams.</li>
<li>The data set contains 30 variables.</li>
</ul>
</div>
</section><section id="description-of-variables-of-interest" class="level2"><h2 class="anchored" data-anchor-id="description-of-variables-of-interest">Description of variables of interest</h2>
<p><br></p>
<div class="small">
<ul>
<li>
<p><strong>Variables of Interest:</strong></p>
<ul>
<li><p><strong>BAME:</strong> Percentage of the team comprised of Black, Asian, or Minority Ethnic employees.</p></li>
<li><p><strong>Function:</strong> Function 1 = Sales staff (customer-facing roles) or 2 = Professional Service (non-customer-facing roles).</p></li>
</ul>
</li>
<li><p>Both variables are of data type double (dbl), in the data set.</p></li>
<li><p>The “BAME” variable is numerical, while the “Function” variable is categorical and needs to be transformed into a factor for R analysis.</p></li>
</ul>
</div>
</section><section id="data-preparation-i" class="level2"><h2 class="anchored" data-anchor-id="data-preparation-i">Data preparation (I)</h2>
<div class="small">
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create a new variable named "profession" with two levels "Sales Staff" and "Professional Service"</span></span>
<span><span class="va">diversity</span> <span class="op">&lt;-</span> <span class="va">diversity</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>profession <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Function</span>,</span>
<span>                           levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">)</span>,</span>
<span>                           labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Sales Staff"</span>, <span class="st">"Professional Service"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># Check levels of the new variable</span></span>
<span><span class="va">diversity</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">distinct</span><span class="op">(</span><span class="va">diversity</span><span class="op">$</span><span class="va">profession</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
  `diversity$profession`
  &lt;fct&gt;                 
1 Professional Service  
2 Sales Staff           
3 &lt;NA&gt;                  </code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Drop "NA" levels as they are not meaningful for the analysis</span></span>
<span><span class="va">diversity_filtered</span> <span class="op">&lt;-</span> <span class="va">diversity</span><span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">profession</span> <span class="op">!=</span> <span class="st">"NA"</span><span class="op">)</span><span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/droplevels.html">droplevels</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check variable levels after dropping "NA" </span></span>
<span><span class="va">diversity_filtered</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">distinct</span><span class="op">(</span><span class="va">profession</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 1
  profession          
  &lt;fct&gt;               
1 Professional Service
2 Sales Staff         </code></pre>
</div>
</div>
</div>
</section><section id="data-preparation-ii" class="level2"><h2 class="anchored" data-anchor-id="data-preparation-ii">Data preparation (II)</h2>
<div class="small">
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#| label: new-data-frame-BAME_profession</span></span>
<span></span>
<span></span>
<span><span class="co"># Creating a new data frame "bame_profession" including variables of interest</span></span>
<span></span>
<span><span class="va">bame_profession</span> <span class="op">&lt;-</span> <span class="va">diversity_filtered</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">BAME</span>, <span class="va">profession</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">bame_profession</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 927
Columns: 2
$ BAME       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ profession &lt;fct&gt; Professional Service, Professional Service, Professional Se…</code></pre>
</div>
</div>
</div>
</section></section><section id="summary-statistics" class="level1"><h1>Summary statistics</h1>
<section id="summary-statistics-1" class="level2"><h2 class="anchored" data-anchor-id="summary-statistics-1">Summary statistics</h2>
<p><br></p>
<div class="small">
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bame_profession</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">profession</span><span class="op">)</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">summarise</span><span class="op">(</span>mean<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">BAME</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            median<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">BAME</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            iqr<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/IQR.html">IQR</a></span><span class="op">(</span><span class="va">BAME</span>, na.rm <span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            sd<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">BAME</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            n<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">BAME</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">kable</span><span class="op">(</span>col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Profession"</span>, <span class="st">"Mean"</span>, <span class="st">"Median"</span>, <span class="st">"IQR"</span>, <span class="st">"Std. Deviation"</span>, <span class="st">"Sum"</span><span class="op">)</span>, align <span class="op">=</span> <span class="st">"cccc"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Profession</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">IQR</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Deviation</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Sum</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sales Staff</td>
<td style="text-align: center;">0.0968317</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.09</td>
<td style="text-align: center;">0.0976745</td>
<td style="text-align: center;">404</td>
</tr>
<tr class="even">
<td style="text-align: center;">Professional Service</td>
<td style="text-align: center;">0.1438596</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">0.1247931</td>
<td style="text-align: center;">342</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="goal">
<div class="small">
<ul>
<li>404 teams within the “Sales Staff” profession and 342 teams within “Professional Service” profession reported the percentages of BAME.</li>
</ul>
</div>
</div>
</section><section id="summary-statistics-density-plot" class="level2"><h2 class="anchored" data-anchor-id="summary-statistics-density-plot">Summary statistics: Density plot</h2>
<div class="small">
<div class="columns">
<div class="column" style="width:75%;">
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">bame_profession</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">BAME</span>, fill<span class="op">=</span><span class="va">profession</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"BAME distribution by Profession"</span>,</span>
<span>      x <span class="op">=</span> <span class="st">"BAME percentage"</span>,</span>
<span>      y <span class="op">=</span> <span class="st">"Density"</span>,</span>
<span>      fill <span class="op">=</span> <span class="st">"Profession"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">scale_fill_manual</span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Sales Staff"</span><span class="op">=</span> <span class="st">"#33645FFF"</span>, <span class="st">"Professional Service"</span> <span class="op">=</span> <span class="st">"#9D1B1FFF"</span> <span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 181 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="slides1_files/figure-html/density-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:25%;">
<p><br><br><br><br></p>
<p>The percentages of BAME employees are lower within “Sales Staff” teams, whereas they are more evenly distributed among “Professional Service” teams.</p>
</div>
</div>
</div>
</section><section id="summary-statistics-boxplots-with-points" class="level2"><h2 class="anchored" data-anchor-id="summary-statistics-boxplots-with-points">Summary statistics: Boxplots with points</h2>
<div class="small">
<div class="columns">
<div class="column" style="width:75%;">
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">bame_profession</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">profession</span>, y<span class="op">=</span> <span class="va">BAME</span>, color <span class="op">=</span> <span class="va">profession</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span> title<span class="op">=</span> <span class="st">"BAME representation by Profession"</span>, </span>
<span>        x<span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>        y<span class="op">=</span> <span class="st">"BAME percentage"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">scale_color_manual</span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Sales Staff"</span><span class="op">=</span> <span class="st">"#33645FFF"</span>, <span class="st">"Professional Service"</span> <span class="op">=</span> <span class="st">"#9D1B1FFF"</span> <span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 181 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 181 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="slides1_files/figure-html/boxplot-with-points-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:25%;">
<p><br><br><br></p>
<p>The distribution of scores of the percentage of BAME employees in the “Professional Service” profession is higher, indicating greater diversity than in the “Sales Staff” profession.</p>
</div>
</div>
</div>
</section><section id="how-does-the-distribution-of-bame-employees-vary-across-different-professions-i" class="level2"><h2 class="anchored" data-anchor-id="how-does-the-distribution-of-bame-employees-vary-across-different-professions-i">How does the distribution of BAME employees vary across different professions? (I)</h2>
<p><br></p>
<div class="small">
<ul>
<li>BAME employees are distributed differently across the two professions. There are more “Sales Staff” teams with a lower percentage of BAME employees, while “Professional Service” teams have a more even distribution.</li>
<li>It’s essential to note that these findings are based on summary statistics and visual examinations, which may not be highly precise.</li>
<li>To gain more confidence in comparing BAME representation between the two professions and to deepen our understanding of the organization’s ethnicity dynamics, we will conduct an Independent Samples t-Test.</li>
</ul>
</div>
</section></section><section id="independent-samples-t-test" class="level1"><h1>Independent Samples t-Test</h1>
<section id="levenes-test-for-equality-of-variances-i" class="level2"><h2 class="anchored" data-anchor-id="levenes-test-for-equality-of-variances-i">Levene’s Test for Equality of Variances (I)</h2>
<div class="small">
<div class="goal">
<p>One of the requirements for the Independent Samples t-Test is the homogeneity of variances (i.e., variances approximately equal across groups).</p>
</div>
<ul>
<li>If this requirement is violated, and the sample sizes for each group differ, we can calculate t-test statistics. The independent samples t-test output also includes an approximate t-statistic, which doesn’t assume equal variances across populations. The Welch t-test statistic can be employed when equal variances between populations cannot be assumed.</li>
</ul>
</div>
</section><section id="levenes-test-for-equality-of-variances-ii" class="level2"><h2 class="anchored" data-anchor-id="levenes-test-for-equality-of-variances-ii">Levene’s Test for Equality of Variances (II)</h2>
<div class="small">
<p><strong>The hypotheses</strong></p>
<ul>
<li>H0: The population variances of “Sales Staff” and “Professional Service” are equal.</li>
<li>H1: The population variances of “Sales Staff” and “Professional Service” are not equal.</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">leveneTest</span><span class="op">(</span><span class="va">bame_profession</span><span class="op">$</span><span class="va">BAME</span>, group <span class="op">=</span> <span class="va">bame_profession</span><span class="op">$</span><span class="va">profession</span>, center<span class="op">=</span><span class="va">mean</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
       Df F value    Pr(&gt;F)    
group   1  35.396 4.141e-09 ***
      744                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>The p-value is 4.141e-09, which is less than 0.05. This indicates very strong evidence against the null hypothesis, leading us to reject the null hypothesis of Levene’s Test.</p></li>
<li><p>This suggests that the variances of the two groups are not equal, meaning the assumption of homogeneity of variances is violated.</p></li>
</ul>
</div>
</section><section id="independent-samples-t-test-i" class="level2"><h2 class="anchored" data-anchor-id="independent-samples-t-test-i">Independent Samples t-Test (I)</h2>
<div class="small">
<ul>
<li>We want to determine if there is a statistically significant difference between the mean percentages of BAME employees in the “Sales Staff” and “Professional Service” professions within this organization.</li>
<li>To achieve this, we can employ an Independent Samples t-Test to compare the means of BAME percentages for “Sales Staff” and “Professional Service.”</li>
</ul>
<p><br></p>
<p><strong>The hypotheses</strong></p>
<ul>
<li>H0: The difference of the means is equal to 0</li>
<li>H1: The difference of the means is not equal to 0.</li>
</ul>
</div>
</section><section id="independent-samples-t-test-ii" class="level2"><h2 class="anchored" data-anchor-id="independent-samples-t-test-ii">Independent Samples t-Test (II)</h2>
<div class="small">
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">bame_profession</span><span class="op">$</span><span class="va">BAME</span> <span class="op">~</span> <span class="va">bame_profession</span><span class="op">$</span><span class="va">profession</span>, var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  bame_profession$BAME by bame_profession$profession
t = -5.7695, df = 744, p-value = 1.166e-08
alternative hypothesis: true difference in means between group Sales Staff and group Professional Service is not equal to 0
95 percent confidence interval:
 -0.06302979 -0.03102614
sample estimates:
         mean in group Sales Staff mean in group Professional Service 
                        0.09683168                         0.14385965 </code></pre>
</div>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">bame_profession</span><span class="op">$</span><span class="va">BAME</span> <span class="op">~</span> <span class="va">bame_profession</span><span class="op">$</span><span class="va">profession</span>, var.equal <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  bame_profession$BAME by bame_profession$profession
t = -5.6553, df = 640.61, p-value = 2.345e-08
alternative hypothesis: true difference in means between group Sales Staff and group Professional Service is not equal to 0
95 percent confidence interval:
 -0.06335727 -0.03069866
sample estimates:
         mean in group Sales Staff mean in group Professional Service 
                        0.09683168                         0.14385965 </code></pre>
</div>
</div>
</div>
</section><section id="independent-samples-t-test-iii" class="level2"><h2 class="anchored" data-anchor-id="independent-samples-t-test-iii">Independent Samples t-Test (III)</h2>
<p><br></p>
<ul>
<li>The result of Levene’s Test suggests that we should consider using the Welch Two Sample t-test because the variances of the two groups are not equal.</li>
<li>The p-value is 2.345e-08 for the t-test for unequal variances, which is less than 0.001. Therefore, we can conclude that there is a significant difference in the mean percentage of BAME employees between the two functions.</li>
</ul></section><section id="how-does-the-distribution-of-bame-employees-vary-across-different-professions-ii" class="level2"><h2 class="anchored" data-anchor-id="how-does-the-distribution-of-bame-employees-vary-across-different-professions-ii">How does the distribution of BAME employees vary across different professions? (II)</h2>
<div class="small">
<ul>
<li>When comparing the “Sales Staff” and “Professional Service” functions, it becomes evident that the mean proportion of BAME staff is significantly lower in “Sales Staff” than in “Professional Service.”</li>
<li>Specifically, the average proportion of BAME staff in teams within the “Sales Staff” function is 9.7%, while in “Professional Service” teams, it stands at 14.39%.</li>
<li>A more in-depth analysis reveals that the likelihood of this difference occurring by chance alone is less than 1 in 1,000, suggesting that there is a significant issue within the “Sales Staff” function that requires attention in the organization.</li>
</ul>
</div>
</section></section><section id="conclusions" class="level1"><h1>Conclusions</h1>
<section id="analyzing-bame-distribution-across-professional-functions" class="level2"><h2 class="anchored" data-anchor-id="analyzing-bame-distribution-across-professional-functions">Analyzing BAME distribution across professional functions</h2>
<div class="small">
<ul>
<li><p>Summary statistics and graphical visualization offer a concise overview of the distribution of BAME employees in the two professions. It’s evident that more “Sales Staff” teams have a lower percentage of BAME employees, while “Professional Service” teams exhibit a more even distribution.</p></li>
<li><p>The results of the independent samples t-test, with a p-value close to 0, confirm a significant difference in the mean percentage of BAME employees between the two functions. This implies that there is an issue that needs attention within the “Sales Staff” function in the organization.</p></li>
</ul>
</div>
</section><section id="recommendations" class="level2"><h2 class="anchored" data-anchor-id="recommendations">Recommendations</h2>
<ul>
<li>According to our analysis, the organization faces challenges in BAME representation across professions, particularly in the “Sales Staff”.</li>
<li>Further research should be conducted to identify the factors influencing or associated with the diversity disparities between these two teams.</li>
</ul>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><script src="https://utteranc.es/client.js" repo="CozminaSecula/blogComments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>