---
title: "R Resources"
title-block-banner: true
format: 
 html: 
  toc: true
execute: 
  echo: false
  warning: false
---

```{r}
#| label: load-libraries


library(DT)

```

# R Resources

[R](https://www.r-project.org/about.html) is an open-source statistical and data visualization software. It supports end-to-end analytics workflows, including data extraction, wrangling, cleaning, analysis, and visualization. All resources in this section are related to R/[R Studio](https://posit.co/products/open-source/rstudio/).

```{r}
#| column: page-right


r_resource <- matrix(c('#{tidyverse} #updatesin2023',
                       '#{dplyr}package #datamanipulation',
                       '#rbasics  #datamanipulation',                                                     '#rupdates  #rcommunity',
                       '#clean data  #draw plots', 
                       '#cheatsheets #functions #posit tools',
               
               
               
               "Summarize the highlights of tidyverse updates that are most relevant to teaching data science with the tidyverse, particularly to new learners.",
               "The most common functions for data manipulation and data management using the {dplyr} package (illustrated on a data frame).",
               "Introduction to data analysis with R, how to create and manipulate vectors, factors, lists and data frames.",
               "There are a lot of great blogs, tutorials, and other resource formats that are coming out daily. R Weekly keeps track of these great things in the R community and makes them accessible to everyone.",
               "This book will teach you how to do data science with R: You’ll learn how to get your data into R, get it into the most useful structure, transform it and visualize.",
               "Concise, quick-reference guides that summarize key concepts, functions, and syntax for popular tools.",
               
               
               
                'Blog post on updates for the {tidyverse} package',
                'Tutorial on using the {dplyr} package',
                'Tutorial on the main functions to manipulate data in R',
                'R Weekly Updates',
                'Free online book',
                'HTML versions of popular cheatsheets',

               
               
               '<a href="https://www.tidyverse.org/blog/2023/08/teach-tidyverse-23/">Teaching the tidyverse in 2023</a>',
               '<a href="https://statsandr.com/blog/introduction-to-data-manipulation-in-r-with-dplyr/">Data manipulation with {dplyr} package</a>',
               '<a href="https://statsandr.com/blog/data-manipulation-in-r/">Data manipulation with base R</a>',
               '<a href="https://rweekly.org/about">Weekly Updates from the Entire R Community</a>',

                '<a href="https://r4ds.hadley.nz/">R for Data Science (2e)</a>',
               '<a href="https://rstudio.github.io/cheatsheets/">Posit Cheatsheets</a>'),
               
               ncol = 4)

colnames(r_resource) <- c('Category', 'Description', 'Type', 'Details')


datatable(r_resource, escape = FALSE) 
          




```
