---
title: "Middle Managers and Diversity & Inclusion: Bridging the Gap for Business Success"
description: "Notes from the article: *Evidence-Based Solutions for* **Inclusion in the Workplace**: *Actions for Middle Managers*"
date: 2023-10-12
categories: [Diversity & Inclusion, Middle Managers]
---

Takeaways from the article [Evidence-Based Solutions for Inclusion in the Workplace: Actions for Middle Managers](https://wpa.wharton.upenn.edu/content/academic-papers/evidence-based-solutions-for-inclusion-in-the-workplace-actions-for-middle-managers/).

Experts at Wharton People Analytics and DiversityInc Media collaborated to investigate and share insights on which diversity and inclusion practices "work" and for which desired workplace outcomes.

In the authors' view, middle managers are crucial to translating diversity and inclusion (D&I) strategies into action for three reasons:

> 1.  Middle managers are central to employees' experiences around inclusion and belonging at work.
>
> 2.  Organizations frequently encounter challenges when trying to put diversity, inclusion, and talent strategies into practice. Middle managers are typically tasked with this responsibility, even though they may have uncertainties about their role or perceive diversity and inclusion efforts as peripheral to their primary job functions.
>
> 3.  It becomes essential for leaders, including middle managers, to shift their perspective from recruitment to a focus on employee retention.

The article focuses on two key findings: **belonging** and **turnover intent**.

It also includes a summary of challenges that companies face in motivating middle managers to incorporate D&I work into their interactions with employees.

# BELONGING

## Belonging: A Key to Employee Engagement and Retention

One of the key findings in the study focuses on the concept of "belonging." Employees who feel they belong, are accepted, and are comfortable in their workplace tend to have higher engagement, performance, promotion, and retention levels. They also have a 50% lower turnover rate than those who feel excluded. Middle managers should be invested in enhancing their direct reports' sense of belonging.

## Mentoring and Sponsorship: A Path to Belonging

The study highlights that mentoring and sponsorship are effective strategies to help employees feel accepted and build their networks. Middle managers can play a crucial role in facilitating these relationships by identifying mentors for their employees and enhancing existing mentor-mentee connections.

## Personal Stories for Inclusion

Another approach that has proven effective is when managers share their personal stories. This encourages their direct reports to share their own experiences, fostering a sense of belonging and acceptance. When employees believe that they are part of an inclusive workplace, they are more likely to stay and contribute to the organization's success.

## Workplace Policies and Middle Managers

During economic upheaval, middle managers should encourage employees to use the company's policies. This support can be instrumental in retaining talent and ensuring a supportive work environment. Middle managers can take ownership in communicating D&I initiatives, encourage team members to utilize relevant programs, and publicly advocate for a flexible approach to meet employees' needs.

# TURNOVER INTENT

Middle managers should also be aware of turnover intent, particularly during challenging economic periods. Losing talent can have a significant impact on teams, and onboarding new employees takes time and resources. Middle managers can reduce turnover intent by actively participating in D&I work, demonstrating their care for their direct reports' success.

## Managerial involvement

Middle managers should collect, compile, synthesize and share feedback on the team's climate to understand what motivates team members to do their jobs well and stay in their current organizations.

## Visibility and Recognition

Visibility plays a crucial role in motivating employees to stay with their current organization. Middle managers can increase their visibility by acknowledging their team members' accomplishments, showcasing underrepresented employees on company websites, and involving a representative sample of team members in discussions and updates.

# The Role of D&I Strategists

D&I strategists should partner with middle managers and help them understand the link between D&I efforts and business challenges. Data and internal analytics can be powerful tools to illustrate the impact of D&I on the workplace.

# Conclusion: Middle Managers as Change Agents

In a world where diversity and inclusion have become integral to business success, middle managers are not just the middlemen but the critical catalysts. Organizations should connect D&I efforts to their business goals, provide clear measures and accountability structures, reward middle managers for their commitment, and ensure transparent communication regarding D&I initiatives.

In this evolving landscape, companies can get middle managers actively involved in D&I efforts by modeling the desired behaviors, creating affinity groups, rewarding champions, providing resources, publishing scorecards for behavioral changes, and inviting middle managers to diversity recruitment fairs.

The journey towards creating a more inclusive workplace is ongoing, and middle managers are poised to be the driving force behind this transformation. Supporting them and providing the tools and insights needed organizations can thrive even in the most challenging times.
